### ISSUE TITLE
Segfault with PHP 7.1 running phan test suite

### ISSUE THREAD

**Issue by remicollet** [nikic/php-ast#36]
```
$ gdb php71
(gdb) run ...phpunit...
...........................................................  63 / 282 ( 22%)
....................................................
Program received signal SIGSEGV, Segmentation fault.
0x00007fffde4e1050 in ast_array_is_list (ast=0x7fffd7411078) at /usr/src/debug/php71-php-ast-0.1.2/NTS/ast.c:244
244			if (list->child[i]->child[1] != NULL || list->child[i]->attr) {
(gdb) bt
#0  0x00007fffde4e1050 in ast_array_is_list (ast=0x7fffd7411078) at /usr/src/debug/php71-php-ast-0.1.2/NTS/ast.c:244
#1  ast_to_zval (zv=zv@entry=0x7fffffff9340, ast=ast@entry=0x7fffd7411078, version=version@entry=30) at /usr/src/debug/php71-php-ast-0.1.2/NTS/ast.c:487
#2  0x00007fffde4e149c in ast_fill_children_ht (ht=0x7fffd79e7d90, ast=ast@entry=0x7fffd74110e8, version=version@entry=30) at /usr/src/debug/php71-php-ast-0.1.2/NTS/ast.c:418
#3  0x00007fffde4e0f1c in ast_to_zval (zv=zv@entry=0x7fffffff9470, ast=ast@entry=0x7fffd74110e8, version=version@entry=30) at /usr/src/debug/php71-php-ast-0.1.2/NTS/ast.c:568
#4  0x00007fffde4e149c in ast_fill_children_ht (ht=0x7fffd7906118, ast=ast@entry=0x7fffd7411018, version=version@entry=30) at /usr/src/debug/php71-php-ast-0.1.2/NTS/ast.c:418
#5  0x00007fffde4e0f1c in ast_to_zval (zv=zv@entry=0x7ffff381aff0, ast=ast@entry=0x7fffd7411018, version=30) at /usr/src/debug/php71-php-ast-0.1.2/NTS/ast.c:568
#6  0x00007fffde4e1c0d in zif_parse_file (execute_data=<optimized out>, return_value=0x7ffff381aff0) at /usr/src/debug/php71-php-ast-0.1.2/NTS/ast.c:661
#7  0x00005555557988fa in dtrace_execute_internal (execute_data=<optimized out>, return_value=<optimized out>) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:107
#8  0x000055555584b4fc in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:1099
#9  0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7fffda133040) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#10 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7fffda133040) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#11 0x000055555584bb5c in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:949
#12 0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7fffd7981380) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#13 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7fffd7981380) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#14 0x000055555584bb5c in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:949
#15 0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7ffff39c2460) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#16 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7ffff39c2460) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#17 0x000055555579a4e1 in zend_call_function (fci=fci@entry=0x7fffffff99f0, fci_cache=<optimized out>, fci_cache@entry=0x7fffffff99c0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_execute_API.c:828
#18 0x00005555556918c9 in reflection_method_invoke (execute_data=<optimized out>, return_value=0x7ffff3819f20, variadic=0) at /usr/src/debug/php-7.1.0RC6/ext/reflection/php_reflection.c:3316
#19 0x00005555557988fa in dtrace_execute_internal (execute_data=<optimized out>, return_value=<optimized out>) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:107
#20 0x000055555584b4fc in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:1099
#21 0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7ffff39a94c0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#22 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7ffff39a94c0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#23 0x000055555584b5ce in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:1076
#24 0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7ffff39a65c0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#25 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7ffff39a65c0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#26 0x000055555584bb5c in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:949
#27 0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7fffda13a000) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#28 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7fffda13a000) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#29 0x000055555584bb5c in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:949
#30 0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7ffff39a5260) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#31 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7ffff39a5260) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#32 0x000055555584bb5c in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:949
#33 0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7ffff39345a0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#34 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7ffff39345a0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#35 0x000055555584bb5c in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:949
#36 0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7ffff39345a0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#37 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7ffff39345a0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#38 0x000055555584bb5c in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:949
#39 0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7ffff39345a0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#40 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7ffff39345a0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#41 0x000055555584bb5c in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:949
#42 0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7ffff39345a0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#43 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7ffff39345a0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#44 0x000055555584bb5c in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:949
#45 0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7fffda11ba20) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#46 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7fffda11ba20) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#47 0x000055555584b5ce in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:1076
#48 0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7ffff38dfc60) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#49 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7ffff38dfc60) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#50 0x000055555584b5ce in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:1076
#51 0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7ffff38825a0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#52 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7ffff38825a0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#53 0x000055555584bb5c in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:949
#54 0x00005555557f2e9b in execute_ex (ex=ex@entry=0x7ffff38593a0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:429
#55 0x0000555555798898 in dtrace_execute_ex (execute_data=0x7ffff38593a0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_dtrace.c:83
#56 0x000055555584db38 in zend_execute (op_array=op_array@entry=0x7ffff3887000, return_value=return_value@entry=0x0) at /usr/src/debug/php-7.1.0RC6/Zend/zend_vm_execute.h:474
#57 0x00005555557a96a3 in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /usr/src/debug/php-7.1.0RC6/Zend/zend.c:1464
#58 0x0000555555746800 in php_execute_script (primary_file=0x7fffffffca10) at /usr/src/debug/php-7.1.0RC6/main/main.c:2533
#59 0x000055555584fd9c in do_cli (argc=4, argv=0x555555bc8230) at /usr/src/debug/php-7.1.0RC6/sapi/cli/php_cli.c:990
#60 0x000055555562116a in main (argc=4, argv=0x555555bc8230) at /usr/src/debug/php-7.1.0RC6/sapi/cli/php_cli.c:1378

```

**Comment by remicollet** [comment]
More exact position, from phpunit --debug

```
Starting test 'Phan\Tests\PhanTest::testFiles with data set "0112_foreach_with_skipped_list.php" (array('./tests/files/src/0112_foreac...st.php'), './tests/files/expected/0112_f...pected')'.
Segmentation fault (core dumped)

```

**Comment by nikic** [comment]
Fixed, thanks!

**Comment by remicollet** [comment]
Indeed, everything ok now.

Great thanks for the quick fix.

**Comment by slokhorst** [comment]
Can you please release a new version which includes this fix? Thanks!

**Comment by nikic** [comment]
Done!
